### ISSUE TITLE
Fixear carrousel

### ISSUE THREAD

**Issue by SelkaChan** [Rober261/pokermortalV2#10]
El carrousel hay que fixearlo, para que ocupe todo el alto del body y que no quede tan feo.
Las imagenes dentro del carrousel hay que ver como se puede hacer para que no se deformen(usar tecnica del enlace):
https://vm.tiktok.com/ZGJHsnw6W/

Las putas flechas de mierda seria un detalle sacarlas fuera del carrousel y ponerlas blancas, sino dejarlas dentro pero hacer que la de la derecha se vea xd

**Comment by Rober261** [comment]
Siguen las putas flechas de mierda.
Excalibur estaba menos fijadas que estas felchas
